### PR TITLE
[FIX #164] Don't crash if multiple windows of the same document are being edited in block editing mode

### LINKED ISSUE #164: Block-Edit Leads to Hang
SEE 5.1.1, iMac Retina 5K, 27-inch, 2017, 40GB RAM, Radeon Pro 580 8GB, MacOS 10.14.6

Had 3 windows open with 2 files in each window (the same 2 files).

Selected a chunk for block edit.
Placed cursor inside blocked area, hit Delete.

It did not delete the character and from that moment forward I could place the cursor anywhere in my file but could not type anything in any window. I chose to Save the files, which thankfully did work. After clicking around for a while, selecting various windows and tabs it got to the point where I could not select anything with the mouse. I finally Quit the app and 2 of the 3 windows closed but 1 stayed open. Finally had to force quit the app to regain control. I lost my highlighted changed text doing the app restart, which really really hurt. :( I wish we could choose when to forget the highlighting on the changed text.

### PR DESCRIPTION
**Pull request by fourplusone**
This PR prevents multiple calls to `[editor storePosition]` and `[editor restorePositionAfterOperations:]` during block editing as these methods require the LayoutManager to perform layout which causes a crash if used between `[textStorage beginEditing]...[textStorage endEditing]`.

Instead, the restoration takes place, after `[textStorage endEditing]` has been called

### CODE REVIEW

File: SubEthaEdit-Mac/Source/PlainTextDocument.m [hunk 1]
```diff
@@ -6354,12 +6354,25 @@ - (BOOL)textView:(NSTextView *)aTextView shouldChangeTextInRange:(NSRange)aAffec
...
+        TCMMMOperation *currentOperation = [TextOperation textOperationWithAffectedCharRange:aAffectedCharRange replacementString:aReplacementString userID:(NSString *)[TCMMMUserManager myUserID]];
+        
+        if (!textStorage.isBlockediting) {
+            // This method will be called within a -beginEditing/-endEditing section if
+            // block editing is active. In this case, the position will not be stored as
+            // it's not possible to ask the layoutmanager for the glyph index while the
+            // storage is being mutated.
+            // The changes will be added to the I_currentTextOperations array.
+            
+            I_currentTextOperations = [NSMutableArray arrayWithObject:currentOperation];
```
Comment (monkeydom) [inline SubEthaEdit-Mac/Source/PlainTextDocument.m]: hmmm - isn't the real fix here not just to guard against blockediting? The array part doesn't seem to be used at all. I think to not store things while blockediting seems like an okay fix, but I wonder if that covers all the cases where this crashes because we query layout at inopportune times.

Comment (monkeydom) [reply SubEthaEdit-Mac/Source/PlainTextDocument.m]: Oh, had a closer look and unsterood the patch fully. Seems good. Will test and probably pull in. Thanks!
